# This service will set the LED pattern

# Operation modes supported
byte SURVEYING=0            # Orange slow flashing
byte CALIBRATING=1          # Purple slow flashing
byte EMERGENCY=2            # Red flashing
byte AVOIDING_WATER=3       # Blue flashing
byte MISSION_DONE_WAITING=4 # Green slow flashing

byte mode # Operation mode enumerated above

---
bool successful # true if the service callback was executed
